[project]
name = "job-scrapping"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.7.0",
    "google-search-results>=2.4.2",
    "ipykernel>=6.29.5",
    "pydantic>=2.10.6",
    "pymongo>=4.11.3",
]
